language: node_js
node_js:
  - "10"

before_script:
  - npm install -g ganache-cli
  - npm install -g truffle

script:
  - git clone https://github.com/neowc/simple-bank-exercise-neowc.git
  - rm ./test/simpleBank.test.js
  - mv ./simple-bank-exercise-neowc.git/test/simpleBank.test.js ./test/simpleBank.test.js
  - ganache-cli &
  - sleep 5
  - truffle test
